### ISSUE TITLE
appflask.py: uncaught ValueError exception with IPv4Network("ipv4_cluster_subnet") with incorrect subnet

### ISSUE THREAD

**Issue by cpaggen** [camrossi/akb#160]
In the /l3out path appflask.py (line 1062) builds node_ipv4 as follows:

node_ipv4 = str(ipaddress.IPv4Interface(primary_ip).ip) + "/" + str(ipaddress.IPv4Network(req.get("ipv4_cluster_subnet")).prefixlen)

the latter part (IPv4Network) produces a ValueError exception when users enter a value such as 192.168.0.10/24 in the UI for the node subnet. The ipaddress library correctly determines host bits are set and raises the exception. We are not catching it so we crash hard.

**Comment by camrossi** [comment]
I think you looked at the line number in the main branch right ? 
The code I shared is dev_1.0rc0 so that would map to line: https://github.com/camrossi/akb/blob/dev_1.0rc0/terraform/appflask.py#L1141

This is indeed a valid crash and the fix is to make the check of the cluster subnet "strict":
https://github.com/camrossi/akb/blob/dev_1.0rc0/terraform/appflask.py#L1124

```
            try:
                # Use the Netwrok to ensure that the mask is always present
                ipaddress.IPv4Network(
                    req.get("ipv4_cluster_subnet"), strict=True) <-- this was False
            except ValueError as e:
                return anchor_node_error(req.get("anchor_nodes"), session['pod_ids'], session['nodes_id'], str(rtr_id_counter), "IPv4 Cluster Subnet Error: " + str(e))
```
