### ISSUE TITLE
Ability to add/remove workers nodes

### ISSUE THREAD

**Issue by camrossi** [camrossi/akb#180]

**Comment by samiib** [comment]
### Create Cluster Page/create cluster page
The UI now reflects the change in appearance of the buttons.
 - The "Apply node config" button only appears when managing the nodes and "Previous+Next" buttons are hidden.
 - Hostname now has an auto-filler and dropdown. 
 - fixed minor typo's within error messages in the UI.
 - cleaned up duplicated CSS from several HTML pages.

**Comment by samiib** [comment]
### Adding nodes when in manage cluster mode now works and doesn’t crash.

- I have removed the jquery from line 145 – 150 in calico_nodes.html file because it was causing multiple post requests when clicking “Add Node” button.
- One post works but the other had no request body, which caused the crash to happen. 
- Although the same code is there for the “Next” button. However, the onclick for saving input overrides the jquery for this button.
